version: '3.8'

services:
  axonserver:
    image: axoniq/axonserver:latest
    container_name: axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    restart: unless-stopped

  db-bank:
    container_name: db-bank
    image: mysql:8.2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cqrs_bank
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./data:/data/db
